<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_healthcare</name>
   <tag></tag>
   <elementGuidId>d29278a9-8137-4b74-b36c-9173a1ff023e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>//input[@id='radio_program_medicaid']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio_program_medicaid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
